#!/bin/bash

# var is integer
declare -i KEEP_WAKED WAIT_FREE

# must keep waked = 1
KEEP_WAKED=1
# wait files to be unlocked by smb and users to be logged out = 1
WAIT_FREE=1

getreserved
if [ $? -ne 0 ]; then
  # not reserved in an hour
  getencoding "$*"
  if [ $? -ne 0 ]; then
    # not encording
    # to be shutdown
    KEEP_WAKED=0
  fi
fi

getsmblock
if [ $? -ne 0 ]; then
  # no files are locked by smb
  getloginusr
  if [ $? -ne 0 ]; then
    # no users
    # to be shutdown
    WAIT_FREE=0
  fi
fi

if [ ${KEEP_WAKED} -eq 0 ]; then
  if [ ${WAIT_FREE} -eq 0 ]; then
    # no reserved, no encoding, not locked, no users
    # now shutdown
    /usr/sbin/shutdown now
    exit 0
    # shell can be closed, but os must run.
  else
    # no reserved, no encoding, but files locked or anyone login
    # shell can be closed, but os must wait files to be unlocked.
    # so, this script to be execute per 5 min.
    nohup bash -c 'sleep 5m; shutdown_srv' &> /dev/null &
    exit 0
  fi
else
  if [ ${WAIT_FREE} -eq 0 ]; then
    # reserved or encoding and not locked or no users
    # this script will be called when finish recording and encoding.
    # shell can be closed, but os must run.
    exit 0
  else
    # reserved or encoding and locked or anyone login
    # this script will be called when finish recording and encoding.
    # shell can be closed, but os must run.
    exit 0
  fi
fi
